Prepare for new release of snowflake which does not have connect_params
PrefectHQ/prefect-dbt pull request #46
Opened 2022-08-04 23:01 UTC by ahuang11

## Summary

## Relevant Issue(s)

## Checklist
- [ ] Summarized PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-dbt/blob/main/CHANGELOG.md)

2022-08-15 22:28 UTC, ahuang11 commented on tests/cli/configs/test_snowflake.py
> -def test_snowflake_target_configs_get_configs_missing_schema():
Removed this because schema is no longer optional in prefect-snowflake

2022-08-15 22:29 UTC, ahuang11 commented
![image](https://user-images.githubusercontent.com/15331990/184731465-686d61a7-04f6-465e-bf5a-e42016a5820d.png)

2022-08-16 11:29 UTC, desertaxle requested changes
Can you pin `prefect-snowflake` to `>= 0.2.0`?

2022-08-16 18:13 UTC, ahuang11 commented
I think I did already in setup.py

2022-08-16 18:50 UTC, desertaxle approved these changes

2022-08-16 18:51 UTC, merged